[workspace]
members=[]
resolver="3"

[workspace.package]
license = "MPL-2.0"
description = "More passkeys and our passkey-based authentication"
repository = "https://github.com/portal-co/pasqi.git"
[workspace.dependencies]
